name: CI-Deploy-Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: fixlabs.work
          port: 22022
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          local_path: ./*
          remote_path: /var/www/fullerton/
          args: '-o ConnectTimeout=5'

      - name: 🐋 Execute Docker commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22022
          script: |
            cd /var/www/fullerton/
            docker compose --env-file docker/prod/.env.production -f docker/prod/compose.yaml build
            docker compose --env-file docker/prod/.env.production -f docker/prod/compose.yaml down
            docker compose --env-file docker/prod/.env.production -f docker/prod/compose.yaml up -d